[workspace]
members = [
  "component-model/*/host-rs",
]

resolver = "2"

[workspace.dependencies]
wasmtime = "21.0.1"
wasmtime-wasi = "21.0.1"
anyhow = "1.0"

[workspace.dependencies.clap]
features = ["derive"]
version = "4"
