[workspace]
members = [
  "component-model/*/host-rs",
]

resolver = "2"

[workspace.dependencies]
wasmtime = "30.0"
wasmtime-wasi = "30.0"
anyhow = "1.0"

[workspace.dependencies.clap]
features = ["derive"]
version = "4"
