[package]
name = "wasip2-hello-world-host"
version = "0.1.0"
edition = "2024"

[dependencies]
wasmtime = "30.0"
wasmtime-wasi = "30.0"
anyhow = "1.0"

[dependencies.clap]
features = ["derive"]
version = "4"
